import * as stylex from '@stylexjs/stylex';

import { colors, fontSize, lineHeight, spacing } from '../styles/tokens.stylex';

export const styles = stylex.create({
  root: {
    backgroundColor: colors.bgWhite,
    borderTopColor: colors.borderLight,
    borderTopStyle: 'solid',
    borderTopWidth: '1px',
    boxSizing: 'border-box',
    display: 'flex',
    width: '100%',
  },
  safeArea: { paddingBottom: 'env(safe-area-inset-bottom)' },
  item: {
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: colors.textSecondary,
    cursor: 'pointer',
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: spacing.xs,
    justifyContent: 'center',
    minHeight: '1.3333rem',
    minWidth: 0,
    paddingBlock: spacing.sm,
    paddingInline: spacing.xs,
    textDecoration: 'none',
  },
  active: { color: colors.primary },
  disabled: { color: colors.textDisabled, cursor: 'not-allowed' },
  iconWrap: { display: 'inline-flex', position: 'relative' },
  icon: { display: 'inline-flex', fontSize: fontSize.xl },
  badge: {
    alignItems: 'center',
    backgroundColor: colors.danger,
    borderRadius: '9999px',
    color: colors.white,
    display: 'inline-flex',
    fontSize: fontSize.xs,
    justifyContent: 'center',
    lineHeight: lineHeight.tight,
    minHeight: '0.32rem',
    minWidth: '0.32rem',
    paddingInline: spacing.xs,
    position: 'absolute',
    right: '-0.2667rem',
    top: '-0.16rem',
  },
  label: {
    fontSize: fontSize.sm,
    lineHeight: lineHeight.tight,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
});
